# USE THIS ON TERMINAL

# --- CREATE USER SUPERADMIN --- #
CREATE USER 'superadmin'@'0.0.0.0' IDENTIFIED BY 'password123';

# --- GRANT ALL PRIVILEGES TO SUPERADMIN AND SET HOST TO 0.0.0.0 --- #
GRANT ALL PRIVILEGES ON *.* TO 'superadmin'@'0.0.0.0';

# --- CHANGE PRIVILEGES IMMEDIATELY TO TAKE EFFECT --- #
FLUSH PRIVILEGES;